inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml

plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2

Lint/EmptyClass:
  AllowComments: true

Naming/PredicateMethod:
  AllowedMethods:
    - call
    - validate_each

# In some cases using more memoized helpers makes specs more readable:
RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/LeakyLocalVariable:
  Enabled: false

# Rubocop counts < RSpec.describe / describe / context / context > as four levels of nesting,
# when in reality it is a reasonable two levels.
# Raising the max from the default to avoid having to refactor lots of tests for no real advantage.
RSpec/NestedGroups:
  Max: 5
